.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH sapm-uninstall 1  "uninstall " 
.SH NAME
sapm\-uninstall \- Uninstall the specified package(s)
.SH SYNOPSIS
\fBsapm uninstall\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIPACKAGES\fR] 
.SH DESCRIPTION
Uninstall the specified package(s)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIPACKAGES\fR]

