.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH sapm-install 1  "install " 
.SH NAME
sapm\-install \- Install the specified package(s)
.SH SYNOPSIS
\fBsapm install\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIPACKAGES\fR] 
.SH DESCRIPTION
Install the specified package(s)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIPACKAGES\fR]

