.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH sapm-find 1  "find " 
.SH NAME
sapm\-find \- Find the specified package
.SH SYNOPSIS
\fBsapm find\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIPACKAGE\fR> 
.SH DESCRIPTION
Find the specified package
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPACKAGE\fR>

