.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH sapm-search 1  "search " 
.SH NAME
sapm\-search \- Search for the specified package
.SH SYNOPSIS
\fBsapm search\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIPACKAGE\fR> 
.SH DESCRIPTION
Search for the specified package
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPACKAGE\fR>

