.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH sapm 1  "sapm 1.0.0" 
.SH NAME
sapm
.SH SYNOPSIS
\fBsapm\fR [\fB\-\-package\-manager\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-\-package\-manager\fR=\fIPACKAGE_MANAGER\fR [default: pacman]
Use the specified package manager instead of the default
.RS
May also be specified with the \fBSAPM_DEFAULT_PACKAGE_MANAGER\fR environment variable. 
.RE
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH SUBCOMMANDS
.TP
sapm\-find(1)
Find the specified package
.TP
sapm\-info(1)
Get information about the specified package
.TP
sapm\-install(1)
Install the specified package(s)
.TP
sapm\-list(1)
List all of the installed packages
.TP
sapm\-uninstall(1)
Uninstall the specified package(s)
.TP
sapm\-update(1)
Update all packages
.SH VERSION
v1.0.0
.SH AUTHORS
Dyredhead
