.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH sapm-info 1  "info " 
.SH NAME
sapm\-info \- Get information about the specified package
.SH SYNOPSIS
\fBsapm info\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIPACKAGE\fR> 
.SH DESCRIPTION
Get information about the specified package
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPACKAGE\fR>

